str="using string functions 2 begin with"
str1="7620657295"
str2="  Ok its not done yet         "
print(str)
print(str.capitalize())
print(str.endswith("with"))
print(str.isalpha())
print(str.isalnum())
print(str.upper())
print(str.isdecimal())
print(str.lower())
print(str.isnumeric())
print(str1.isdigit())
print(str.isspace())
print(str.encode('UTF-8',errors='strict'))
print(str.istitle())
print(len(str1))
print(str2.lstrip())
print(max(str1))
print(max(str2))#MAximum alphabet or no. in the given string
print(min(str))#minimum alpah returns space this time
print(min(str2))
print(str2.startswith('Ok'))
#print(str1.translate(table,deletechars"o"))
print(str2.zfill(25))
print(str.replace("u","o"))
print(str2.rstrip())
print(str2.center(55,'c'))
print(str.swapcase())
print(str1.swapcase())
#print(str2.rindex(str2,beg=0,end=len(str2)))
print(str2.split())
print(str2.strip())
print(str.join(str1))
print(str.count("i"))